import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";

const sathoshi = LocalFont({
  src: "../public/font/Satoshi-Variable.ttf",
  variable: "--font-sathoshi",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sathoshi.variable} antialiased bg-[hsl(220,15%,12%)] w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
